#!/bin/bash

export TERM=xterm-256color
arr=($(/home/pi/scripts/RPiMS/redis-get.py))
SENSOR_TEMP=$(echo ${arr[0]}|sed s/Temp=//)
SENSOR_HUM=$(echo ${arr[1]}|sed s/Humidity=//)
SENSOR_PRESSURE=$(echo ${arr[2]}|sed s/Pressure=//)
CPU_TEMP=$(vcgencmd measure_temp|awk -F\= '{print $2}')

echo "$(tput setaf 2)
   .~~.   .~~.
  '. \ ' ' / .'$(tput setaf 1)
   .~ .~~~..~.
  : .~.'~'.~. :$(tput sgr0)  Raspberry Pi Monitoring System$(tput setaf 1)
 ~ (   ) (   ) ~ $(tput sgr0)Room Pressure.....: $SENSOR_PRESSURE$(tput setaf 1)
( : '~'.~.'~' : )$(tput sgr0)Room Humidity.....: $SENSOR_HUM$(tput setaf 1)
 ~ .~ (   ) ~. ~ $(tput sgr0)Room Temperature..: $SENSOR_TEMP$(tput setaf 1)
  (  : '~' :  )  $(tput sgr0)CPU Temperature...: $CPU_TEMP$(tput setaf 1)
   '~ .~~~. ~'
       '~'
$(tput sgr0)"

echo
