#!/bin/bash

export TERM=xterm-256color
IFS='; '
SENSOR_TYPE="BME280 1"  #Use BME280 1,2 or 3
str=$(/home/pi/scripts/RPiMS/redis-get-data.py $SENSOR_TYPE)
read -r -a arr <<< "$str"
SENSOR_TEMP=$(echo ${arr[0]}|awk -F[=] '{print $2" °C"}')
SENSOR_HUM=$(echo ${arr[1]}|awk -F[=] '{print $2" %"}')
SENSOR_PRESSURE=$(echo ${arr[2]}|awk -F[=] '{print $2" hPa"}')
CPU_TEMP=$(vcgencmd measure_temp|awk -F[=\'] '{print $2" °C"}')


echo "$(tput setaf 2)
   .~~.   .~~.
  '. \ ' ' / .'$(tput setaf 1)
   .~ .~~~..~.
  : .~.'~'.~. :$(tput sgr0)  Raspberry Pi Monitoring System$(tput setaf 1)
~ (   ) (   ) ~  $(tput sgr0)Room Pressure.....: $SENSOR_PRESSURE$(tput setaf 1)
( : '~'.~.'~' : )$(tput sgr0)Room Humidity.....: $SENSOR_HUM$(tput setaf 1)
 ~ .~ (   ) ~. ~ $(tput sgr0)Room Temperature..: $SENSOR_TEMP$(tput setaf 1)
  (  : '~' :  )  $(tput sgr0)CPU Temperature...: $CPU_TEMP$(tput setaf 1)
   '~ .~~~. ~'
       '~'
$(tput sgr0)"

echo

_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "RPiMS address is %s\n" "$_IP"
fi
