---
####
setup:
  verbose: false
  show_sys_info: true
  use_system_buttons: false
  use_contact_led_indicator: false
  use_digital_led_indicator: false
  use_contact_sensor: true
  use_digital_sensor: true
  use_bme280_sensor: true
  use_ds18b20_sensor: false
  use_dht_sensor: false
  use_cpu_sensor: true
  use_weather_station: false
  use_zabbix_agent: false
  use_picamera: false
  use_picamera_recording: false
  use_serial_display: true
zabbix_agent:
  TLSAccept: psk
  TLSConnect: psk
  TLSPSK: ff70fbfb074adcec3a89e4e4e47f61031947d722b88cab9c5c1b9232696492c8
  TLSPSKFile: /opt/RPiMS/config/zabbix_rpims.psk
  TLSPSKIdentity: acea516a1191b9c5
  Timeout: 3
  hostname: rpims.home
  location: My Home
  chassis: embedded
  deployment: RPiMS
  zabbix_server: zabbix.home
  zabbix_server_active: zabbix.home
sensors:
  CPU:
    temp:
      read_interval: 1
  PICAMERA:
    fps: 24
    mode: 6
    vflip: false
    hflip: false
    hr: 1280
    vr: 720
  BME280:
    id1:
      id: id1
      interface: i2c
      name: Room 1
      read_interval: 2
      use: false
      i2c_address: 118
    id2:
      id: id2
      interface: serial
      name: Room 2
      read_interval: 2
      use: false
      serial_port: USB1
    id3:
      id: id3
      interface: serial
      name: Room 3
      read_interval: 6
      use: true
      serial_port: USB4
  ONE_WIRE:
    DS18B20:
      read_interval: 5
      addresses: {}
  DHT:
    name: Outoor
    pin: 17
    read_interval: 60
    type: DHT11
  WEATHER:
    RAINFALL:
      acquisition_time: 60
      agregation_time: 3600
      sensor_pin: 22
      use: true
    WIND:
      DIRECTION:
        acquisition_time: 6
        adc_input: 1
        adc_type: AutomationPhat
        reference_voltage_adc_input: 2
        use: true
      SPEED:
        acquisition_time: 6
        agregation_time: 3600
        sensor_pin: 23
        use: true
gpio:
  GPIO_5:
    pin: 5
    type: DigitalSensor
    name: Motion sensor - Room
    hold_time: 1
  GPIO_6:
    pin: 6
    type: DigitalSensor
    name: Light sensor - Room
    hold_time: 1
  GPIO_12:
    pin: 12
    type: ContactSensor
    name: Door sensor - Room
    hold_time: 1
  GPIO_13:
    pin: 13
    type: DigitalSensor
    name: Motion sensor - Kitchen
    hold_time: 1
  GPIO_16:
    pin: 16
    type: ContactSensor
    name: Flood sensor - Kitchen
    hold_time: 5
  GPIO_18:
    pin: 18
    type: ContactSensor
    name: Door sensor - Kitchen
    hold_time: 1
  GPIO_19:
    pin: 19
    type: led
    name: Relay  1
    hold_time: 1
  GPIO_20:
    pin: 20
    type: led
    name: Relay 2
    hold_time: 1
  GPIO_21:
    pin: 21
    type: motion_led
    name: Digital Indicator
    hold_time: 1
  GPIO_26:
    pin: 26
    type: door_led
    name: Contact Indicator
    hold_time: 1
serial_bus_display:
  bus_display_type: i2c
  display_type: oled_sh1106
  display_refresh_rate: 10
  display_rotate: 0
